### PR TITLE
refactor: Refactoring the landing page code.

### PR DESCRIPTION
**Pull request by Akaikenlol**
refactor: Refactoring the landing page code architecture. 
style: Adding icon.

### CODE REVIEW

**Comment by Rickaym** [comment]
Hey mate,
You are committing `package-lock.json` from npm. The app is intended to use the pnpm package manager instead of npm due to several performance and caching reasons. Can you remove it and set your project up with pnpm instead?

**Comment by Akaikenlol** [comment]
Okay, I will remove it.

**Comment by Rickaym** [comment]
Great, thanks. Is pnpm working well for you?

**Review by Rickaym — APPROVED** [review]
LGTM

**Pull request merged**
