### PR TITLE
feature/landing-page-and-new-api-route

### PR DESCRIPTION
**Pull request by SaiSeng18**
Is this ok? I think the landing page should be at the home page instead of the "Create a Project" button?

### CODE REVIEW

**Comment by Rickaym** [comment]
Hey,
Yes, the landing page should be at the root along with the "Create a project" button (which is named "Get started for free" in the design document at the moment. Practically, when we launch the app, the landing page will be at workesque.com and the app pages will be at app.workesque.com.

I noticed that the landing page was in a separate folder at the moment. Is there a reason for this? If not we can move it into the root page where the create a project button is.

**Comment by SaiSeng18** [comment]
I don't really have a reason. I'm just making sure not to make any conflicts. I didn't want to touch the button until I make sure so I made a separate folder. I will fix it later.

**Comment by Rickaym** [comment]
Ah, I thought so. That is good, I will leave this PR for your fix.
Also, I would suggest one small adjustment to your workflow. Before you begin any work, start by creating an issue, and then create a branch inside the issue. This way, other contributors can look to the list of issues to not accidently work on the same thing even if it's not PRed.

**Comment by SaiSeng18** [comment]
Noted

**Review by Rickaym — APPROVED** [review]
LGTM

**Comment by Rickaym** [comment]
Rebased for merging onto main.

**Pull request merged**
