### PR TITLE
feature/calendar-view

### PR DESCRIPTION
**Pull request by SaiSeng18**
Add a fully functioning, real time calendar. You can change the month and render every day of the month which you can also see the data/events of that day on the calendar itself or at the bottom of the calendar. You can also change the day by clicking the number on the date. I also add a popup form with a plus button on each day.

### CODE REVIEW

**Comment by Rickaym** [comment]
Hi brother,

I'm not sure if you're able to see Cloudflare Page's build log but there is a compilation error. I have attached it down below for reference.

```
5:35:49.957 | ./src/app/(dashboard)/project/components/Kaban.tsx:92:11
-- | --
15:35:49.957 | Type error: Property 'id' does not exist on type 'Over \| null'.
15:35:49.957 |  
15:35:49.957 | 90 \| 		const { active, over } = event;
15:35:49.957 | 91 \| 		const { id } = active;
15:35:49.958 | > 92 \| 		const { id: overId } = over;
15:35:49.958 | \| 		        ^
15:35:49.958 | 93 \|
15:35:49.958 | 94 \| 		// Find the containers
15:35:49.958 | 95 \| 		const activeContainer = findContainer(id);
15:35:50.213 | Failed: Error while executing user command. Exited with error code: 1
```

**Comment by SaiSeng18** [comment]
Hey bro,

Actually I can’t see the log. Now that I saw it, yes there was a problem
with types which seem confusing. You can have a look at it and fix it if
you can solve the problem. That will be a great help.

**Comment by Rickaym** [comment]
Sure thing, I will check the code and see.

**Comment by SaiSeng18** [comment]
Ohh I fixed the errors. Though I don't know if the cloudflare is still building or I still got another error which I can't see the log.

**Comment by Rickaym** [comment]
Ah, here is the new error.

```
20:59:54.344 | ./src/utils/dummyData.ts:1:10
-- | --
20:59:54.344 | Type error: Module '"@/app/(dashboard)/project/components/Kaban"' has no exported member 'TaskProps'. Did you mean to use 'import TaskProps from "@/app/(dashboard)/project/components/Kaban"' instead?
20:59:54.344 |  
20:59:54.345 | > 1 \| import { TaskProps } from "@/app/(dashboard)/project/components/Kaban";
20:59:54.345 | \|          ^
20:59:54.345 | 2 \|
20:59:54.345 | 3 \| export const dummyDatas: TaskProps[] = [
20:59:54.345 | 4 \| 	{
20:59:54.588 | Failed: Error while executing user command. Exited with error code: 1
```

**Comment by SaiSeng18** [comment]
Can you merge these? These are ready.

**Comment by Rickaym** [comment]
Amazing work.

**Review by Rickaym — APPROVED** [review]
Looks good.

**Pull request merged**
